-- Xóa các bảng cũ nếu đã tồn tại để tránh lỗi "relation already exists"
DROP TABLE IF EXISTS 
    Roles, Users, Pets, Service_categories, Services, 
    Doctor_schedules, Appointments, Appointment_services, 
    Medical_records, Medicines, Prescriptions, Prescription_items, 
    Vaccines, Vaccination_records, Posts, Invoices, Invoice_items, Reviews, Notifications CASCADE;

-- 1. Create Roles
CREATE TABLE Roles (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR(50) NOT NULL
);

-- 2. Create Users (Đã thêm Soft Delete)
CREATE TABLE Users (
    ID UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    Role_id BIGINT REFERENCES Roles(ID),
    Full_name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL,
    Phone VARCHAR(20),
    Password_hash TEXT,
    Avatar TEXT,
    Gender SMALLINT,
    Date_of_birth DATE,
    Address TEXT,
    Is_active BOOLEAN DEFAULT true,
    Created_at TIMESTAMPTZ DEFAULT now(),
    Deleted_at TIMESTAMPTZ -- [UPDATE] Cột xóa mềm
);

-- 3. Create Pets (Đã thêm Soft Delete)
CREATE TABLE Pets (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Owner_id UUID REFERENCES Users(ID),
    Name VARCHAR(255) NOT NULL,
    Species VARCHAR(100),
    Breed VARCHAR(100),
    Gender SMALLINT,
    Birth_date DATE,
    Weight NUMERIC(5,2),
    Color VARCHAR(100),
    Blood_type VARCHAR(20),
    Sterilized BOOLEAN,
    Microchip_code VARCHAR(100),
    Allergy_note TEXT,
    Created_at TIMESTAMPTZ DEFAULT now(),
    Deleted_at TIMESTAMPTZ -- [UPDATE] Cột xóa mềm
);

-- 4. Create Service Categories
CREATE TABLE Service_categories (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Deleted_at TIMESTAMPTZ -- [UPDATE] Cột xóa mềm
);

-- 5. Create Services (Đã thêm Soft Delete)
CREATE TABLE Services (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Category_id BIGINT REFERENCES Service_categories(ID),
    Name VARCHAR(255) NOT NULL,
    Price NUMERIC(12,2) NOT NULL,
    Duration_minutes INT,
    Description TEXT,
    Is_active BOOLEAN DEFAULT true,
    Deleted_at TIMESTAMPTZ -- [UPDATE] Cột xóa mềm
);

-- 6. Create Doctor Schedules
CREATE TABLE Doctor_schedules (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Doctor_id UUID REFERENCES Users(ID),
    Work_date DATE NOT NULL,
    Start_time TIME NOT NULL,
    End_time TIME NOT NULL,
    Max_appointments INT,
    Is_available BOOLEAN DEFAULT true,
    Deleted_at TIMESTAMPTZ -- [UPDATE] Cột xóa mềm
);

-- 7. Create Appointments (ĐÃ XÓA Service_id, Thêm Soft Delete)
CREATE TABLE Appointments (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Pet_id BIGINT REFERENCES Pets(ID),
    Customer_id UUID REFERENCES Users(ID),
    Doctor_id UUID REFERENCES Users(ID),
    Appointment_date DATE NOT NULL,
    Start_time TIME,
    End_time TIME,
    Status VARCHAR(50) DEFAULT 'Pending',
    Symptom TEXT,
    Note TEXT,
    Created_by UUID REFERENCES Users(ID),
    Created_at TIMESTAMPTZ DEFAULT now(),
    Deleted_at TIMESTAMPTZ -- [UPDATE] Cột xóa mềm
);

-- 8. [BẢNG MỚI] Appointment Services (Giải quyết vấn đề 1 hẹn - nhiều dịch vụ)
CREATE TABLE Appointment_services (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Appointment_id BIGINT REFERENCES Appointments(ID) ON DELETE CASCADE,
    Service_id BIGINT REFERENCES Services(ID) ON DELETE CASCADE
);

-- 9. Create Medical Records (Đã thêm Soft Delete)
CREATE TABLE Medical_records (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Appointment_id BIGINT REFERENCES Appointments(ID),
    Doctor_id UUID REFERENCES Users(ID),
    Weight NUMERIC(5,2),
    Temperature NUMERIC(4,1),
    Heart_rate INT,
    Symptoms TEXT,
    Diagnosis TEXT,
    Treatment_plan TEXT,
    Note TEXT,
    Follow_up_date DATE,
    Created_at TIMESTAMPTZ DEFAULT now(),
    Deleted_at TIMESTAMPTZ -- [UPDATE] Cột xóa mềm
);

-- 10. Create Medicines (Đã thêm Soft Delete)
CREATE TABLE Medicines (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Unit VARCHAR(50),
    Stock_quantity INT DEFAULT 0,
    Import_price NUMERIC(12,2),
    Sell_price NUMERIC(12,2),
    Expiry_date DATE,
    Description TEXT,
    Deleted_at TIMESTAMPTZ -- [UPDATE] Cột xóa mềm
);

-- 11. Create Prescriptions
CREATE TABLE Prescriptions (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Medical_record_id BIGINT REFERENCES Medical_records(ID),
    Doctor_id UUID REFERENCES Users(ID),
    Note TEXT,
    Created_at TIMESTAMPTZ DEFAULT now(),
    Deleted_at TIMESTAMPTZ -- [UPDATE] Cột xóa mềm
);

-- 12. Create Prescription Items
CREATE TABLE Prescription_items (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Prescription_id BIGINT REFERENCES Prescriptions(ID) ON DELETE CASCADE,
    Medicine_id BIGINT REFERENCES Medicines(ID),
    Dosage VARCHAR(100),
    Frequency VARCHAR(100),
    Duration_days INT,
    Quantity INT,
    Instruction TEXT
);

-- 13. Create Vaccines (Đã thêm Soft Delete)
CREATE TABLE Vaccines (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Manufacturer VARCHAR(255),
    Description TEXT,
    Deleted_at TIMESTAMPTZ -- [UPDATE] Cột xóa mềm
);

-- 14. Create Vaccination Records
CREATE TABLE Vaccination_records (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Pet_id BIGINT REFERENCES Pets(ID),
    Vaccine_id BIGINT REFERENCES Vaccines(ID),
    Appointment_id BIGINT REFERENCES Appointments(ID),
    Doctor_id UUID REFERENCES Users(ID),
    Injection_date DATE,
    Next_due_date DATE,
    Reaction_note TEXT,
    Deleted_at TIMESTAMPTZ -- [UPDATE] Cột xóa mềm
);

-- 15. Create Posts (Đã thêm Soft Delete)
CREATE TABLE Posts (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    Slug VARCHAR(255) UNIQUE NOT NULL,
    Thumbnail TEXT,
    Content TEXT,
    Author_id UUID REFERENCES Users(ID),
    Status VARCHAR(50) DEFAULT 'Published',
    Created_at TIMESTAMPTZ DEFAULT now(),
    Deleted_at TIMESTAMPTZ -- [UPDATE] Cột xóa mềm
);

-- 16. Create Invoices (Đã thêm Soft Delete)
CREATE TABLE Invoices (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Appointment_id BIGINT REFERENCES Appointments(ID),
    Subtotal NUMERIC(12,2),
    Discount_amount NUMERIC(12,2) DEFAULT 0,
    Total_amount NUMERIC(12,2),
    Payment_status VARCHAR(50) DEFAULT 'Unpaid',
    Payment_method VARCHAR(50),
    Paid_at TIMESTAMPTZ,
    Created_at TIMESTAMPTZ DEFAULT now(),
    Deleted_at TIMESTAMPTZ -- [UPDATE] Cột xóa mềm
);

-- 17. Create Invoice Items
CREATE TABLE Invoice_items (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Invoice_id BIGINT REFERENCES Invoices(ID) ON DELETE CASCADE,
    Item_type VARCHAR(50), -- Ví dụ: 'Service', 'Medicine', 'Vaccine'
    Item_id BIGINT,
    Item_name VARCHAR(255),
    Quantity INT,
    Unit_price NUMERIC(12,2),
    Total_price NUMERIC(12,2)
);

-- 18. Create Reviews
CREATE TABLE Reviews (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Customer_id UUID REFERENCES Users(ID),
    Appointment_id BIGINT REFERENCES Appointments(ID),
    Rating SMALLINT CHECK (Rating >= 1 AND Rating <= 5),
    Comment TEXT,
    Created_at TIMESTAMPTZ DEFAULT now(),
    Deleted_at TIMESTAMPTZ -- [UPDATE] Cột xóa mềm
);

-- 19. Create Notifications
CREATE TABLE Notifications (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    User_id UUID REFERENCES Users(ID) ON DELETE CASCADE,
    Title VARCHAR(255) NOT NULL,
    Content TEXT NOT NULL,
    Type VARCHAR(50),
    Reference_id BIGINT,
    Is_read BOOLEAN DEFAULT false,
    Created_at TIMESTAMPTZ DEFAULT now(),
    Deleted_at TIMESTAMPTZ -- [UPDATE] Cột xóa mềm
);
